package br.com.financialcontrol.infrastructure.persistence

import br.com.financialcontrol.application.FinanceRepository
import br.com.financialcontrol.domain.*
import jakarta.persistence.*
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Component
import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.YearMonth
import java.util.UUID
import kotlin.jvm.optionals.getOrNull

@Entity @Table(name = "users") class UserJpa(@Id var id: UUID = UUID.randomUUID(), var name: String = "", var email: String = "", @Column(name = "created_at") var createdAt: LocalDateTime = LocalDateTime.now())
@Entity @Table(name = "banks") class BankJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), var name: String = "", var code: String? = null, @Enumerated(EnumType.STRING) var type: BankType = BankType.BANK)
@Entity @Table(name = "accounts") class AccountJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), @Column(name = "bank_id") var bankId: UUID = UUID.randomUUID(), var name: String = "", @Enumerated(EnumType.STRING) var type: AccountType = AccountType.CHECKING)
@Entity @Table(name = "categories") class CategoryJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), var name: String = "", var color: String = "#888888", var active: Boolean = true)
@Entity @Table(name = "credit_cards") class CardJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), @Column(name = "bank_id") var bankId: UUID = UUID.randomUUID(), var name: String = "", @Column(name = "last_four_digits") var lastFourDigits: String = "", @Column(name = "limit_amount") var limitAmount: BigDecimal = BigDecimal.ZERO, @Column(name = "closing_day") var closingDay: Int = 1, @Column(name = "due_day") var dueDay: Int = 1, var active: Boolean = true)
@Entity @Table(name = "card_invoices", uniqueConstraints = [UniqueConstraint(columnNames = ["credit_card_id", "reference_month"])]) class InvoiceJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "credit_card_id") var creditCardId: UUID = UUID.randomUUID(), @Column(name = "reference_month") var referenceMonth: String = "", @Column(name = "closing_date") var closingDate: LocalDate = LocalDate.now(), @Column(name = "due_date") var dueDate: LocalDate = LocalDate.now(), @Enumerated(EnumType.STRING) var status: InvoiceStatus = InvoiceStatus.OPEN)
@Entity @Table(name = "subscriptions") class SubscriptionJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), @Column(name = "category_id") var categoryId: UUID = UUID.randomUUID(), @Column(name = "credit_card_id") var creditCardId: UUID? = null, @Column(name = "account_id") var accountId: UUID? = null, var name: String = "", var amount: BigDecimal = BigDecimal.ZERO, @Enumerated(EnumType.STRING) var frequency: SubscriptionFrequency = SubscriptionFrequency.MONTHLY, @Column(name = "charge_day") var chargeDay: Int = 1, var active: Boolean = true)
@Entity @Table(name = "expenses") class ExpenseJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "user_id") var userId: UUID = UUID.randomUUID(), @Column(name = "category_id") var categoryId: UUID = UUID.randomUUID(), @Column(name = "account_id") var accountId: UUID? = null, @Column(name = "credit_card_id") var creditCardId: UUID? = null, @Column(name = "subscription_id") var subscriptionId: UUID? = null, var description: String = "", var merchant: String? = null, @Column(name = "purchase_date") var purchaseDate: LocalDate = LocalDate.now(), @Column(name = "total_amount") var totalAmount: BigDecimal = BigDecimal.ZERO, @Enumerated(EnumType.STRING) @Column(name = "payment_method") var paymentMethod: PaymentMethod = PaymentMethod.PIX, @Enumerated(EnumType.STRING) var status: ExpenseStatus = ExpenseStatus.PENDING, @Column(name = "created_at") var createdAt: LocalDateTime = LocalDateTime.now())
@Entity @Table(name = "expense_installments") class InstallmentJpa(@Id var id: UUID = UUID.randomUUID(), @Column(name = "expense_id") var expenseId: UUID = UUID.randomUUID(), @Column(name = "invoice_id") var invoiceId: UUID? = null, var number: Int = 1, var total: Int = 1, var amount: BigDecimal = BigDecimal.ZERO, @Column(name = "due_date") var dueDate: LocalDate = LocalDate.now(), @Enumerated(EnumType.STRING) var status: ExpenseStatus = ExpenseStatus.PENDING)

interface UserJpaRepository : JpaRepository<UserJpa, UUID> { fun existsByEmail(email: String): Boolean }
interface BankJpaRepository : JpaRepository<BankJpa, UUID> { fun findAllByUserId(userId: UUID): List<BankJpa> }
interface AccountJpaRepository : JpaRepository<AccountJpa, UUID> { fun findAllByUserId(userId: UUID): List<AccountJpa> }
interface CategoryJpaRepository : JpaRepository<CategoryJpa, UUID> { fun findAllByUserId(userId: UUID): List<CategoryJpa> }
interface CardJpaRepository : JpaRepository<CardJpa, UUID> { fun findAllByUserId(userId: UUID): List<CardJpa> }
interface InvoiceJpaRepository : JpaRepository<InvoiceJpa, UUID> { fun findByCreditCardIdAndReferenceMonth(cardId: UUID, month: String): InvoiceJpa? }
interface SubscriptionJpaRepository : JpaRepository<SubscriptionJpa, UUID> { fun findAllByUserId(userId: UUID): List<SubscriptionJpa> }
interface ExpenseJpaRepository : JpaRepository<ExpenseJpa, UUID> { fun findAllByUserId(userId: UUID): List<ExpenseJpa> }
interface InstallmentJpaRepository : JpaRepository<InstallmentJpa, UUID> { fun findAllByExpenseId(expenseId: UUID): List<InstallmentJpa>; fun findAllByDueDateBetween(start: LocalDate, end: LocalDate): List<InstallmentJpa> }

@Component
class PostgresFinanceRepository(private val users: UserJpaRepository, private val banks: BankJpaRepository, private val accounts: AccountJpaRepository, private val categories: CategoryJpaRepository, private val cards: CardJpaRepository, private val invoices: InvoiceJpaRepository, private val subscriptions: SubscriptionJpaRepository, private val expenses: ExpenseJpaRepository, private val installments: InstallmentJpaRepository) : FinanceRepository {
    override fun saveUser(user: User) = users.save(UserJpa(user.id, user.name, user.email, user.createdAt)).domain()
    override fun user(id: UUID) = users.findById(id).getOrNull()?.domain(); override fun emailExists(email: String) = users.existsByEmail(email)
    override fun saveBank(bank: Bank) = banks.save(BankJpa(bank.id, bank.userId, bank.name, bank.code, bank.type)).domain(); override fun banks(userId: UUID) = banks.findAllByUserId(userId).map { it.domain() }; override fun bank(id: UUID) = banks.findById(id).getOrNull()?.domain()
    override fun saveAccount(account: Account) = accounts.save(AccountJpa(account.id, account.userId, account.bankId, account.name, account.type)).domain(); override fun accounts(userId: UUID) = accounts.findAllByUserId(userId).map { it.domain() }; override fun account(id: UUID) = accounts.findById(id).getOrNull()?.domain()
    override fun saveCategory(category: Category) = categories.save(CategoryJpa(category.id, category.userId, category.name, category.color, category.active)).domain(); override fun categories(userId: UUID) = categories.findAllByUserId(userId).map { it.domain() }; override fun category(id: UUID) = categories.findById(id).getOrNull()?.domain()
    override fun saveCard(card: CreditCard) = cards.save(CardJpa(card.id, card.userId, card.bankId, card.name, card.lastFourDigits, card.limitAmount, card.closingDay, card.dueDay, card.active)).domain(); override fun cards(userId: UUID) = cards.findAllByUserId(userId).map { it.domain() }; override fun card(id: UUID) = cards.findById(id).getOrNull()?.domain()
    override fun saveSubscription(subscription: Subscription) = subscriptions.save(SubscriptionJpa(subscription.id, subscription.userId, subscription.categoryId, subscription.creditCardId, subscription.accountId, subscription.name, subscription.amount, subscription.frequency, subscription.chargeDay, subscription.active)).domain(); override fun subscriptions(userId: UUID) = subscriptions.findAllByUserId(userId).map { it.domain() }
    override fun saveExpense(expense: Expense) = expenses.save(ExpenseJpa(expense.id, expense.userId, expense.categoryId, expense.accountId, expense.creditCardId, expense.subscriptionId, expense.description, expense.merchant, expense.purchaseDate, expense.totalAmount, expense.paymentMethod, expense.status, expense.createdAt)).domain(); override fun expense(id: UUID) = expenses.findById(id).getOrNull()?.domain(); override fun expenses(userId: UUID) = expenses.findAllByUserId(userId).map { it.domain() }
    override fun saveInstallments(items: List<ExpenseInstallment>) { installments.saveAll(items.map { InstallmentJpa(it.id, it.expenseId, it.invoiceId, it.number, it.total, it.amount, it.dueDate, it.status) }) }; override fun installmentsForExpense(expenseId: UUID) = installments.findAllByExpenseId(expenseId).map { it.domain() }
    override fun installmentsBetween(userId: UUID, start: LocalDate, end: LocalDate): List<ExpenseInstallment> { val owned = expenses.findAllByUserId(userId).map { it.id }.toSet(); return installments.findAllByDueDateBetween(start, end).filter { it.expenseId in owned }.map { it.domain() } }
    override fun invoice(cardId: UUID, month: YearMonth) = invoices.findByCreditCardIdAndReferenceMonth(cardId, month.toString())?.domain(); override fun saveInvoice(invoice: CardInvoice) = invoices.save(InvoiceJpa(invoice.id, invoice.creditCardId, invoice.referenceMonth.toString(), invoice.closingDate, invoice.dueDate, invoice.status)).domain()
}
private fun UserJpa.domain() = User(id, name, email, createdAt); private fun BankJpa.domain() = Bank(id, userId, name, code, type); private fun AccountJpa.domain() = Account(id, userId, bankId, name, type); private fun CategoryJpa.domain() = Category(id, userId, name, color, active); private fun CardJpa.domain() = CreditCard(id, userId, bankId, name, lastFourDigits, limitAmount, closingDay, dueDay, active); private fun InvoiceJpa.domain() = CardInvoice(id, creditCardId, YearMonth.parse(referenceMonth), closingDate, dueDate, status); private fun SubscriptionJpa.domain() = Subscription(id, userId, categoryId, creditCardId, accountId, name, amount, frequency, chargeDay, active); private fun ExpenseJpa.domain() = Expense(id, userId, categoryId, accountId, creditCardId, subscriptionId, description, merchant, purchaseDate, totalAmount, paymentMethod, status, createdAt); private fun InstallmentJpa.domain() = ExpenseInstallment(id, expenseId, invoiceId, number, total, amount, dueDate, status)
